export class ContactForm {
  id: number = 0
  name: string = ''
  email: string = ''
  phone: string = ''
  message: string = ''
  expectedPvPower: number = 0
  energyConsumptionPerYear: number = 0
  calculationDate: any = null
  customerType: string = ''
  mountType: string = ''
  proposedPvPower: number = 0
  inverterModel: string = ''
  priceFrom: number = 0
  priceTo: number = 0
  modulePower: number = 0
  moduleModel: string = '';
  panelsQuantity: number = 0;
  vatTax: number = 0;
}
